{"created": "2020-11-23 22:11:20.777906", "duration": 2.4584243297576904, "exitcode": 0, "root": "group2", "summary": {"passed": 3, "total": 3, "collected": 3}, "tests": [{"nodeid": "services/test_challenge_service.py::test_get_mode_count", "outcome": "passed", "metadata": {"id": "UT ChallengeService.1", "description": "Verify that the get_mode_count returns the correct data"}}, {"nodeid": "services/test_challenge_service.py::test_get_challenge_content", "outcome": "passed", "metadata": {"id": "UT ChallengeService.2", "description": "Verify that the correct attribute/data is returned"}}, {"nodeid": "services/test_challenge_service.py::test_save_challenge_results", "outcome": "passed", "metadata": {"id": "UT ChallengeService.3", "description": "Verify that data comes is saved as expected with additional fields included"}}], "warnings": [{"message": "urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!", "category": "RequestsDependencyWarning", "when": "collect", "filename": "C:\\Users\\Sarah\\Anaconda3\\lib\\site-packages\\requests\\__init__.py", "lineno": 80}], "success": false}