{"created": "2020-11-28 21:52:30.831695", "duration": 0.8886229991912842, "exitcode": 0, "root": "group2", "summary": {"passed": 3, "xpassed": 1, "total": 4, "collected": 4}, "tests": [{"nodeid": "managements/test_user_management.py::test_create_user[valid user-success0]", "outcome": "passed", "metadata": ""}, {"nodeid": "managements/test_user_management.py::test_create_user[valid user-success1]", "outcome": "passed", "metadata": ""}, {"nodeid": "managements/test_user_management.py::test_create_user[invalid user-error]", "outcome": "passed", "metadata": ""}, {"nodeid": "managements/test_user_management.py::test_login", "lineno": 15, "outcome": "xpassed", "keywords": ["xfail", "group2", "managements/test_user_management.py", "pytestmark", "test_login"], "setup": {"duration": 0.00028249999999996334, "outcome": "passed"}, "call": {"duration": 0.00044440000000001145, "outcome": "passed"}, "teardown": {"duration": 0.00030530000000006385, "outcome": "passed"}}], "success": false}